version: '3.8'

services:
  backend:
    image: node:20
    container_name: backend
    working_dir: "/usr/src/app"
    volumes:
      - ./back-end:/usr/src/app
    environment:
      - FRONT_URL=http://localhost:3000
      - MONGO_URI=mongodb://admin:admin123@mongo:27017
      - SESSION_SECRET=TEST123
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    command: >
      sh -c "npm install && npm run start-dev"

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin 
      MONGO_INITDB_ROOT_PASSWORD: admin123 
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
    driver: local
